# Use root/example as user/password credentials
version: '3.1'

volumes:
  mysql-data:

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
  
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
